### ISSUE TITLE
Remove bold text and alacritty theme

### ISSUE THREAD

**Issue by darhsn** [bignimbus/pop-punk.vim#6]
I like your colorscheme, but it would be cool if you add an option to remove all the bolds, and please can you make an alacritty theme. I would love it!

**Comment by darhsn** [comment]
This is the alacritty theme that I did for your theme
```yaml
# Pop punk alacritty theme
colors:
    # Default colors
    primary:
        background: '#000000'
        foreground: '#ffffff'

    # Normal colors
    normal:
        black:   '#000000'
        red:     '#d70061'
        green:   '#5ff967'
        yellow:  '#ffff00'
        blue:    '#0088ff'
        magenta: '#c526ff'
        cyan:    '#40e0d0'
        white:   '#ffffff'

    # Bright colors
    bright:
        black:   '#000000'
        red:     '#ff005f'
        green:   '#5ff967'
        yellow:  '#ffff00'
        blue:    '#306b8f'
        magenta: '#c526ff'
        cyan:    '#c526ff'
        white:   '#ffffff'
```
